version: "3"
volumes:
  volume_database_project:

###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###

services:
  mysql:
    image: mysql:8.0
    container_name: project_mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_DATABASE: marketplace
      MYSQL_USER: marketplace
      MYSQL_PASSWORD: marketplace
    volumes:
      - volume_database_project:/var/lib/mysql
      - ./.docker/data/marketplace.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: project_phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "81:80"

  web:
    build: ./.docker
    container_name: project_web
    volumes:
      - ./:/var/www/html
      - ./.docker/virtualhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./.docker/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    ports:
      - "80:80"
    depends_on:
      - mysql

###< doctrine/doctrine-bundle ###
